[package]
name = "plonky2-circuits"
version = "0.1.0"
edition = "2021"

[dependencies]
plonky2 = "0.2.2"
starky = "0.4.0"
anyhow = "1.0.86"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"